# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_analog_ov_0_0/design_1_analog_ov_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_analog_ov_0_0 || ORIG_REF_NAME==design_1_analog_ov_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ov7725_data_sample_0_0/design_1_ov7725_data_sample_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ov7725_data_sample_0_0 || ORIG_REF_NAME==design_1_ov7725_data_sample_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_3_0/design_1_system_ila_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_3_0 || ORIG_REF_NAME==design_1_system_ila_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_4_0/design_1_system_ila_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_4_0 || ORIG_REF_NAME==design_1_system_ila_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ila_0_1/design_1_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ila_0_1 || ORIG_REF_NAME==design_1_ila_0_1} -quiet] -quiet

# XDC: c:/Users/SUXP/Desktop/ov7725/vivado_debug_1/project_1/project_1.gen/sources_1/bd/design_1/design_1_ooc.xdc
