# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/SUXP/Desktop/ov7725/video_in_to_axis/project_1/project_1.srcs/sources_1/ip/v_vid_in_axi4s_0/v_vid_in_axi4s_0.xci
# IP: The module: 'v_vid_in_axi4s_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SUXP/Desktop/ov7725/video_in_to_axis/project_1/project_1.gen/sources_1/ip/v_vid_in_axi4s_0/v_vid_in_axi4s_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_vid_in_axi4s_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/SUXP/Desktop/ov7725/video_in_to_axis/project_1/project_1.gen/sources_1/ip/v_vid_in_axi4s_0/v_vid_in_axi4s_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_vid_in_axi4s_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/SUXP/Desktop/ov7725/video_in_to_axis/project_1/project_1.srcs/sources_1/ip/v_vid_in_axi4s_0/v_vid_in_axi4s_0.xci
# IP: The module: 'v_vid_in_axi4s_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SUXP/Desktop/ov7725/video_in_to_axis/project_1/project_1.gen/sources_1/ip/v_vid_in_axi4s_0/v_vid_in_axi4s_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_vid_in_axi4s_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/SUXP/Desktop/ov7725/video_in_to_axis/project_1/project_1.gen/sources_1/ip/v_vid_in_axi4s_0/v_vid_in_axi4s_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_vid_in_axi4s_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
